### ISSUE TITLE
Monomorphic Lenses?

### ISSUE THREAD

**Issue by CodaFi** [typelift/Focus#2]
The other Swift Lens framework, `Monocle`, has taken to a data-accessor-esque implementation of Lenses, and I think there's something to the idea of including a record-accessor structure with Focus.  Especially since Swift doesn't allow polymorphic type aliases, and Monomorphic lenses are just _easier_ to reason about for the general Swift programmer.

**Comment by pthariensflame** [comment]
Well, we could make them all classes, and have monomorphic subclasses with injections from the superclasses at appropriate type parameters

Ideally, Swift would have generic type aliases, but no.  :(

**Comment by CodaFi** [comment]
That leaves us open to subclassing, and I'm not really up for taking that risk.  Maybe it could work that way internally, then expose a `struct` for each leaf of the inheritance tree... but that sounds like a nasty hack.

**Comment by pthariensflame** [comment]
Actually, as long as we force subclassers to implement a `fold`-like method, subclassing isn't a problem!  (Well, barring malicious intent, which is impossible to guard against anyway in this language.  :P  )

Once #1 is merged, I'll start looking at how to make that happen; it may even make usage of the library easier in certain cases, by allowing the direct implementation of `Lens`es, etc., where passing closures to an initializer may be somewhat inefficient.

**Comment by CodaFi** [comment]
I'll take your word for it then.  I look forward to seeing that pull request!

**Comment by pthariensflame** [comment]
With #9 merged, this is now maybe a little more possible.  We should look into it again.
